### ISSUE TITLE
Add Ckeditor's markdown plugin

### ISSUE THREAD

**Issue by Yaco** [ColdTrick/ckeditor_extended#10]
Hi!
I would really appreciate if you could include the [Ckeditor's markdown plugin](http://ckeditor.com/addon/markdown). I tried to do it myself, expended some hours, but still getting JS related errors. Since you have much more expertise, I hope you can add this improvement.

Would be awesome to be able to write in Elgg directly into Markdown.

Thanks in advance and congratulations for your amazing work!

**Comment by jdalsem** [comment]
Development on this plugin has stopped
