### ISSUE TITLE
"The provided file is not an image" when sending to server an image file

### ISSUE THREAD

**Issue by michelesbw** [ColdTrick/ckeditor_extended#11]
Hello,
when I try to upload an image from relevant button and tab, after clicking on "Send to server" I receive the following error "The provided file is not an image". I tried several files and formats, all ok but none was upoaded (jpeg,jpg,png,..).
I'm on Elgg 2.3 and CKEditorExtended 2.1
Cheers

**Comment by jdalsem** [comment]
A BC workaround has been implemented. Thanks for reporting

Related Elgg Core bug is discovered here: https://github.com/Elgg/Elgg/issues/10686

**Comment by michelesbw** [comment]
Hello :)
I just tried to update via composer and the issue is still there, maybe my costraint "^2.0" doesn't help, right?
Cheers

**Comment by jdalsem** [comment]
You are correct... your constraint limits you to stable releases... i expect to create a new release end of this week. If you are in a hurry, you need to change your constraint, but that will be 'risky'.
