### ISSUE TITLE
want to add atd-ckeditor with this plugin

### ISSUE THREAD

**Issue by dipenpatel235** [ColdTrick/ckeditor_extended#12]
hello i have follow below link steps to add in your elgg plugin but it is not working.
so can you please help me to add below plugin used in youe elgg plugin ?

https://github.com/Automattic/atd-ckeditor

Thanks

**Comment by jdalsem** [comment]
if you followed all the steps and it is not working, you should look if you have any errors. Maybe the AtD plugin requires a specific version of ckeditor, or maybe you have issues with the proxy config. First verify that the plugin is loaded (as part of the ckeditor config) and configured as described in the documentation of the AtD.

If that is all correct, then i can not help you any further and you should contact the plugin developer. I will reopen this ticket if you think ckeditor_extended causes an issue.
