### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'returnValue.extraPlugins.split')

### ISSUE THREAD

**Issue by Beaufort8** [ColdTrick/ckeditor_extended#13]
CK-Editor do not render - I get an JavaScript-Error in Safari, Firefox and Chrome.

**Comment by jdalsem** [comment]
is there a bug in your configuration regarding to extraPlugins? Maybe a space or special char that is not allowed?

**Comment by Beaufort8** [comment]
Thanx for your hint! In fact, my old configuration is not compatible with the new CK editor version.
