### ISSUE TITLE
Ckeditor is not showing any option

### ISSUE THREAD

**Issue by merilturock** [ColdTrick/ckeditor_extended#14]
Hi,
   When i activate this plugin my ckeditor does not show bold, italic those tools see image below. through the console i found the following error.. but i don't know how to fix them.

Uncaught TypeError: Cannot read property 'split' of undefined
    at elgg.js:151
    at callHookHandler (elgg.js:97)
    at elgg.js:90
    at Array.forEach (<anonymous>)
    at elgg.js:90
    at Array.forEach (<anonymous>)
    at elgg.ElggPriorityList.forEach (elgg.js:90)
    at elgg.js:100
    at Array.every (<anonymous>)
    at Object.elgg.trigger_hook (elgg.js:100)

![ckeditor error](https://user-images.githubusercontent.com/1689530/31344763-3e9b8ec0-ad31-11e7-9b0b-dea17da02164.PNG)

**Comment by jdalsem** [comment]
This is probably due to a javascript error. Look in your browser console for more information
