### ISSUE TITLE
Javascript Error on Elgg3.2 - ckeditor_extended version 4

### ISSUE THREAD

**Issue by Ngseri** [ColdTrick/ckeditor_extended#20]
I am working on upgrading my site from Elgg2.3 to 3.2 and I use ckeditor_extended plugin. I have no issue with Elgg2.3 but I got this below error whenever I visit a page that has CKeditor in it.

**_Uncaught Error: [CKEDITOR.resourceManager.add] The resource name "filetools" is already registered.
    at window.CKEDITOR.window.CKEDITOR.dom.CKEDITOR.resourceManager.add (ckeditor.js:251)
    at ckeditor.js:1244
    at ckeditor.js:2096_**

![Screen Shot 2020-02-20 at 1 06 32 PM](https://user-images.githubusercontent.com/8534322/74964721-e2709f00-53e1-11ea-9950-31d6ffd50afe.png)

**Comment by jdalsem** [comment]
did you try to clear the settings of the plugin? Maybe because of the upgrade a conflicting setting is the result of this error.

**Comment by Ngseri** [comment]
No I did not clear the plugin settings. I'm going to try that. Thanks jdalsem!

**Comment by Ngseri** [comment]
I tried clearing the plugin settings and flush the caches. But the same issue wasn't solved.

**Comment by jdalsem** [comment]
Which version of ckeditor_extended are you using?

**Comment by Ngseri** [comment]
4.0

**Comment by jdalsem** [comment]
Unfortunately i am unable to reproduce this issue with the latest version of this plugin and on Elgg 3.3.3. Could there be anything else influencing the configuration of the editor?

**Comment by Ngseri** [comment]
I do not see any plugins triggering/calling 'filetools' in webroot/mod directory except ckeditor_extended plugin.

**Comment by jdalsem** [comment]
Still unable to reproduce with latest version
