### ISSUE TITLE
Add the ability to create folders in image upload capability

### ISSUE THREAD

**Issue by olairmarcos** [ColdTrick/ckeditor_extended#5]
Congratulations on this plugin. I would suggest a new feature for the plugin.
- Add a button to delete images from the user owner. Unused images.
- Ability to create and delete folder to have a better organization of the image files on the screen.

Thank attention. good work

**Comment by olairmarcos** [comment]
Hello
I am used elgg1.9 and install ckeditor extend 1.0. In version 1.0 for elgg1.9 not appear the button to delete image on the server, the user image list. In version 1.1 for elgg 1.12.4 the pugin works correctly and shows the button to delete the image from the list.
It can add functionality, image delete button in order to delete the image of the user image list for the plugin ckeditor_extend to elgg 1.9.
I really appreciate your kindness, good work.

**Comment by jdalsem** [comment]
I would suggest you upgrade to the most recent version of Elgg. We are not going to add the delete function to the 'older' functionality.

Adding a folder functionality is a good wish, so i am renaming the title of this issue

**Comment by jdalsem** [comment]
Development on this plugin has stopped
