### ISSUE TITLE
When will support Elgg 2.0?

### ISSUE THREAD

**Issue by beautylix** [ColdTrick/ckeditor_extended#6]
It does not support elgg 2.0 currently, would you please release an edition to support it asap?

**Comment by beautylix** [comment]
there are at least 2 questions;
1, editor window does now show, it shows a text input area
2, images uploaded before do not show

please fix it soon, thanks a lot

**Comment by jdalsem** [comment]
Fixed in https://github.com/ColdTrick/ckeditor_extended/commit/9f266ef4547def1fdb12520b5c03743688c70848
