### ISSUE TITLE
setting styles for specific visual editor to the comments box

### ISSUE THREAD

**Issue by olairmarcos** [ColdTrick/ckeditor_extended#7]
It is possible to create a setting styles for specific visual editor (minimal) to the comments box or even be able to disable visual editor for comments? How can I make through the configuration panel CKeditor_extended plugin?
Thank you for your help.

**Comment by jdalsem** [comment]
This is (due to some limitations in Elgg) very hard to achieve, but is is on my personal wishlist a long time. Maybe it is time for me to submit a Pull Request to Elgg to make this happen. At least in this plugin it will not be added.
