### ISSUE TITLE
Uncaught TypeError: elggCKEditor.bind is not a function

### ISSUE THREAD

**Issue by juho-jaakkola** [ColdTrick/ckeditor_extended#9]
I haven't investigated much yet, but the error seems to be originating from here: https://github.com/ColdTrick/ckeditor_extended/blob/305ead25fb36704cd8863822c8b2a41a2e478135/views/default/output/inline_edit.php#L29

Tested on Elgg 2.2.0.

**Comment by jdalsem** [comment]
hmm... works for me, but not yet tested on 2.2.x...

**Comment by teamwebgalli** [comment]
Sorry Jerome, problem still exits with 
- Elgg version 2.3.0
- CK editor V 1.9
- CK editor extended version 2.0

**Comment by jdalsem** [comment]
A lot has been changed since this was reported. Can not confirm this on latest versions.
